## Put contents to update an existing character

PUT http://localhost:3000/api/v1/characters/1
Content-Type: application/json
{
  "name": "Albert Wesker",
  "alias": "The Mastermind",
  "abilities": ["Superhuman Strength", "Regeneration", "Telekinesis", "Enhanced Agility"],
  "affiliation": "Umbrella Corporation"
}